version: 0.2

env:
  shell: bash
  parameter-store:
    GIT_USER: "/CodeBuild/Git_USER"
    GIT_PASS: "/CodeBuild/Git_PASS"

phases:
  install:
    commands:
      - echo Executing install phase
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $CODEBUILD_SOURCE_REPO_URL
      - echo $CODEBUILD_SOURCE_VERSION

      - echo $CODEBUILD_WEBHOOK_MERGE_COMMIT
      - echo $CODEBUILD_WEBHOOK_PREV_COMMIT
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo $CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID
      - echo $CODEBUILD_WEBHOOK_EVENT
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - echo $CODEBUILD_WEBHOOK_BASE_REF

  pre_build:
    commands:
      - echo Executing pre_build phase
      # for nightly builds/tests use develop branch
      - export CODEBUILD_GIT_BRANCH="develop"
      - export CODEBUILD_GIT_BRANCH_FV3CORE="release-stable";
      - export GIT_BASE_BRANCH="develop"
      - export CODEBUILD_GIT_BRANCH_FV3CORE="release-stable";


      # Upload branch name and commit sha as CodeBuild artifact to S3
      - mkdir -p /jcsda/artifacts
      - echo ${CODEBUILD_GIT_BRANCH} > /jcsda/artifacts/branch_name.txt
      - echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} > /jcsda/artifacts/commit_sha.txt

      - cd CI
      - source /opt/spack-environment/activate.sh
      - source /opt/intel/oneapi/compiler/latest/env/vars.sh
      - source /opt/intel/oneapi/mpi/latest/env/vars.sh

      # read cdash url from s3
      - wget https://ci-test-cdash-url.s3.amazonaws.com/cdash_url.txt
      - CDASH_URL=$(cat cdash_url.txt)

      #  Setting git credentials
      - sed -i '/ssh/d' ~/.gitconfig
      - sed '/instead/d' ~/.gitconfig
      - git config --global credential.helper store
      - touch ~/.git-credentials
      - chmod 0700 ~/.git-credentials
      - echo "https://${GIT_USER}:${GIT_PASS}@github.com" >~/.git-credentials

      # FV3-JEDI (testing repo)
      - ./clone.sh jcsda-internal/fv3-jedi $CODEBUILD_GIT_BRANCH /jcsda/fv3-bundle fv3-jedi ${GIT_BASE_BRANCH}  develop

      # fv3-jedi-lm
      - ./clone.sh jcsda-internal/fv3-jedi-linearmodel $CODEBUILD_GIT_BRANCH /jcsda/fv3-bundle fv3-jedi-lm ${GIT_BASE_BRANCH} develop

      # ioda
      - ./clone.sh jcsda-internal/ioda $CODEBUILD_GIT_BRANCH /jcsda/fv3-bundle ioda ${GIT_BASE_BRANCH} develop

      # gsibec
      - git clone --depth 1 -b 1.1.2 https://github.com/geos-esm/GSIbec /jcsda/fv3-bundle/gsibec

      # saber
      - ./clone.sh jcsda-internal/saber $CODEBUILD_GIT_BRANCH /jcsda/fv3-bundle saber ${GIT_BASE_BRANCH} develop

      # oops
      - ./clone.sh jcsda-internal/oops $CODEBUILD_GIT_BRANCH /jcsda/fv3-bundle oops ${GIT_BASE_BRANCH} develop

      # ufo
      - ./clone.sh jcsda-internal/ufo $CODEBUILD_GIT_BRANCH /jcsda/fv3-bundle ufo ${GIT_BASE_BRANCH} develop

      # vader
      - ./clone.sh jcsda-internal/vader $CODEBUILD_GIT_BRANCH /jcsda/fv3-bundle vader ${GIT_BASE_BRANCH} develop

      # crtm
      - ./clone.sh jcsda/CRTMv3 $CODEBUILD_GIT_BRANCH /jcsda/fv3-bundle crtm ${GIT_BASE_BRANCH} develop

      # femps
      - ./clone.sh jcsda-internal/femps $CODEBUILD_GIT_BRANCH /jcsda/fv3-bundle femps ${GIT_BASE_BRANCH} develop

      # fms
      - ./clone.sh jcsda/FMS $CODEBUILD_GIT_BRANCH_FV3CORE  /jcsda/fv3-bundle fms ${GIT_BASE_BRANCH_FV3CORE} release-stable

      # GFDL_atmos_cubed_sphere
      - ./clone.sh jcsda/GFDL_atmos_cubed_sphere $CODEBUILD_GIT_BRANCH_FV3CORE /jcsda/fv3-bundle fv3 ${GIT_BASE_BRANCH_FV3CORE} release-stable

      #  internal repos
      # geos-aero
      - ./clone.sh jcsda-internal/geos-aero $CODEBUILD_GIT_BRANCH /jcsda/fv3-bundle geos-aero ${GIT_BASE_BRANCH} develop

      # ropp
      - ./clone.sh jcsda-internal/ropp-test $CODEBUILD_GIT_BRANCH /jcsda/fv3-bundle ropp-ufo ${GIT_BASE_BRANCH} develop

      # fv3-jedi-test
      - ./clone.sh jcsda-internal/fv3-jedi-data $CODEBUILD_GIT_BRANCH /jcsda/fv3-bundle fv3-jedi-data ${GIT_BASE_BRANCH} develop

      # ioda-data
      - ./clone.sh jcsda-internal/ioda-data $CODEBUILD_GIT_BRANCH /jcsda/fv3-bundle ioda-data ${GIT_BASE_BRANCH} develop

      # ufo-data
      - ./clone.sh jcsda-internal/ufo-data $CODEBUILD_GIT_BRANCH /jcsda/fv3-bundle ufo-data ${GIT_BASE_BRANCH} develop


      # move CMakeLists.txt
      - cp CMakeLists_nightly.txt /jcsda/fv3-bundle/CMakeLists.txt
      - cp -r cmake /jcsda/fv3-bundle/
      # cdash upload setup
      - cp /jcsda/fv3-bundle/cmake/CTestConfig_nightly.cmake /jcsda/fv3-bundle/CTestConfig.cmake
      - sed -i "s@CDASH_URL@$CDASH_URL@g" /jcsda/fv3-bundle/CTestConfig.cmake

      - chmod 777 -R /jcsda/fv3-bundle

  build:
    on-failure: CONTINUE
    commands:
      - echo Executing build phase
      - echo $CODEBUILD_BUILD_SUCCEEDING
      - export BUILD_STATUS="0"
      - echo $BUILD_STATUS

      - mkdir /build_container
      - chmod 777 /build_container

      - export FV3JEDI_TEST_TIER=2
      - cd /build_container
      # for jedi-cmake
      - export jedi_cmake_ROOT=/opt/view

      - ecbuild -Wno-dev -DCMAKE_BUILD_TYPE=Release -DCDASH_OVERRIDE_GIT_BRANCH=$CODEBUILD_GIT_BRANCH -DCDASH_OVERRIDE_SITE=NightlyCodeBuild -DCDASH_OVERRIDE_SYSTEM_NAME=IntelContainer -DCTEST_UPDATE_VERSION_ONLY=FALSE -DBUNDLE_SKIP_GEOS-AERO=OFF -DBUNDLE_SKIP_ROPP-UFO=OFF -DBUNDLE_SKIP_GSIBEC=OFF /jcsda/fv3-bundle/
      - make -j2

      - echo $CODEBUILD_BUILD_SUCCEEDING
      - if [ "$CODEBUILD_BUILD_SUCCEEDING" = "1" ];
        then export BUILD_STATUS="1";
        echo "Build passed";
        fi
      - echo $BUILD_STATUS

      - cd /build_container
      - ctest -D NightlyTest

    finally:
      # upload ctest report to CDASH
      - cd /build_container
      - ctest -D NightlySubmit -M Nightly -- --track Nightly --group Nightly

  post_build:
    commands:

      # upload find cdash url and upload it as CodeBuild artifact to S3
      - if [ "$BUILD_STATUS" = "1" ];
        then echo "Build & tests passed, find cdash url";
        url=$(bash /jcsda/fv3-bundle/fv3-jedi/CI/cdash-url.sh /build_container/Testing $CDASH_URL);
        echo $url;
        echo ${url} > /jcsda/artifacts/cdash-url.txt;
        cat /jcsda/artifacts/cdash-url.txt;
        else echo "Build failed";
        fi
      - echo Executing post_build phase
      - echo $CODEBUILD_BUILD_SUCCEEDING
      - echo $BUILD_STATUS
